version: '3.7'

services:
  reverseproxy:
    build:
      context: .
      dockerfile: nginx/nginx.local.Dockerfile
    networks:
      gateway:
        aliases:
          - "id-local.globomantics.com"   
    restart: always
    ports:
      - "44395:44395"     

  identityserver:
    depends_on:
      - reverseproxy 
      - smtp4dev      
      - globsql
      - seq
    build:
      context: .
      dockerfile: Globomantics.IdentityServer/Dockerfile
    networks:
      - gateway
    environment:
      - ASPNETCORE_URLS=http://*:5000      
    ports:
      - "5003:5000"      

  smtp4dev:
    image: rnwood/smtp4dev    
    networks:
      - gateway
    ports:      
      - '5013:80'  # Web interface      
      - '2523:25'  # SMTP server      
      - '144:143'  # IMAP server

  seq:    
    image: datalust/seq
    restart: always
    networks:
      - gateway
    ports:
      - '5333:80'
      - '5343:5341'
    environment:
      - ACCEPT_EULA=Y      

  globsql:
    build:
      context: .
      dockerfile: sql/sql.Dockerfile
    networks:
      - gateway
    environment:      
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=Sqlc0ntainersFTW!
    ports:
      - "1435:1433"      

networks:
  gateway: {}